name: 'Cache Go dependencies and test results'
runs:
  using: "composite"
  steps:
  - shell: bash
    run: echo 'PREFIX=${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-matrix(${{ join(matrix.*,'|') }})' >> $GITHUB_ENV
  - uses: actions/cache@v2
    with:
      path: ~/go/pkg/mod
      key: ${{ env.PREFIX }}-go-mod-${{ hashFiles('**/go.sum') }}
      restore-keys: ${{ env.PREFIX }}-go-mod
  - uses: actions/cache@v2
    if: ${{ github.ref != 'master' }}
    with:
      path: ~/.cache/go-build
      key: ${{ env.PREFIX }}-go-build-${{ github.ref }}-${{ hashFiles('**', '!.git') }}
      restore-keys: |
        ${{ env.PREFIX }}-go-build-${{ github.ref }}
        ${{ env.PREFIX }}-go-build
