name: 'Cache Go dependencies and test results'
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ github.workflow }}-${{ github.job }}-${{ matrix.go }}-${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ github.workflow }}-${{ github.job }}-${{ matrix.go }}-${{ runner.os }}-go-mod
    - uses: actions/cache@v2
      if: ${{ github.ref != 'master' }}
      with:
        path: ~/.cache/go-build
        key: ${{ github.workflow }}-${{ github.job }}-${{ matrix.go }}-${{ runner.os }}-go-all-${{ github.ref }}-${{ hashFiles('**', '!.git') }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-${{ matrix.go }}-${{ runner.os }}-go-all-${{ github.ref }}
          ${{ github.workflow }}-${{ github.job }}-${{ matrix.go }}-${{ runner.os }}-go-all
