name: 'Cache Go dependencies and test results'
runs:
  using: "composite"
  steps:

  # Set the modification time of all files to a fixed time. `git clone` sets the
  # modification time to the current time, but Go tests that access fixtures get
  # invalidated if their modification times change. Setting a fixed time
  # improves cache hits.
  - shell: bash
    run: touch -m -t '202201010101' $(find . -not -path '.git/*')

  # The PREFIX must uniquely identify the specific instance of a job executing.
  - shell: bash
    run: echo 'PREFIX=${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-matrix(${{ join(matrix.*,'|') }})' >> $GITHUB_ENV

  # Cache the Go Modules downloaded during the job.
  - uses: actions/cache@v2
    with:
      path: ~/go/pkg/mod
      key: ${{ env.PREFIX }}-go-mod-${{ hashFiles('**/go.sum') }}
      restore-keys: ${{ env.PREFIX }}-go-mod

  # Cache any build and test artifacts during the job, which will speed up
  # rebuilds and cause test runs to skip tests that have no reason to rerun.
  # Don't run this for protected branches like master/main.
  - uses: actions/cache@v2
    if: ${{ github.ref_protected || github.ref != 'master' || github.ref != 'main' }}
    with:
      path: ~/.cache/go-build
      key: ${{ env.PREFIX }}-go-build-${{ github.ref }}-${{ hashFiles('**', '!.git') }}
      restore-keys: |
        ${{ env.PREFIX }}-go-build-${{ github.ref }}
        ${{ env.PREFIX }}-go-build
