name: 'Horizon release'

on:
  push:
    tags: ['horizon-v.*']
    # TODO: Branch enabled temporarily, to test the code, remove before merging!
    branches: ['migrate-circle-to-actions']
  pull_request:

jobs:
  publish_artifacts:
    working_directory: /go/src/github.com/stellar/go
    docker:
      - image: golang:1.17
    steps:
      - check_deprecations
      - install_go_deps
      - check_go_deps
      - build_packages
      - attach_workspace:
          at: ./dist
      - name: Publish release on GitHub
        uses: actions/upload-release-asset@v1
        env:
          # TODO: make sure this variable exists
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./dist/*
          command: |
            if [ "$(ls -A ./dist)" ]
            then
              go get github.com/tcnksm/ghr@v0.14.0
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./dist/
            else
                echo "No files found in ./dist. No binaries to publish for ${CIRCLE_TAG}."
            fi

  push-horizon-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push to DockerHub
          uses: docker/build-push-action@v2
          with:
            # TODO: Commented out until we disable the CircleCI jobs
            # push: true
            tags: stellar/horizon:latest
            secrets: |
              GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
